version: '3'
services:
  php:
    build: .
    image: 'php:8.1-apache'
    container_name: php
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=idk
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']